<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/07/14 12:31:38

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobet',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
