<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2020/07/14 13:14:59

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'pgsql:host=localhost;dbname=jobeet',
  'username' => 'postgres',
  'password' => 'musavi88',
  'name' => 'doctrine',
)),);
